spring:
  application:
    name: fade
  datasource:
    url: jdbc:mysql://localhost:3306/fade
    username: root
    password: root
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: false
  sql.init.mode: always
