spring:
  profiles:
    active: local
    group:
      local:
        - common
        - local
      prod:
        - common
        - prod

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: prod